### PR TITLE
add sponsor logos to homepage

### PR DESCRIPTION
**Pull request by pjawneh**

### CODE REVIEW

**Comment by f3ltron** [comment]
thank's for the pr pjaneh can you remove yarn lock and package lock modification please ?

**Comment by f3ltron** [comment]
and we will merge it after

**Comment by f3ltron** [comment]
i did it for you thank's 👍

**Comment by pjawneh** [comment]
Okay, thank you!

**Comment by T0RAT0RA** [comment]
@f3ltron I'm curious, why did you delete the `package-lock.json` file in this PR?
I didn't see changes to the dependencies

**Comment by f3ltron** [comment]
i didnt check the update but anyway we should not change lock files if we are not having new package or update version

**Pull request merged**
