### PR TITLE
fix css scoped bug

### LINKED ISSUE #125: I think there is a css problem with some conflicts css
image in event are to small 
and socials are not align in flex

### PR DESCRIPTION
**Pull request by aurelienroux**
resolves #125

### CODE REVIEW

**Comment by f3ltron** [comment]
can you try to put the slider back ?

**Comment by tlebel** [comment]
> can you try to put the slider back ?

Which slider are we talking about here?

**Comment by f3ltron** [comment]
@aurelienroux implemented a slider for event pictures that didnt work as expected with generate because of the css bug i think. The component already exist

**Comment by tlebel** [comment]
> @aurelienroux implemented a slider for event pictures that didnt work as expected with generate because of the css bug i think. The component already exist

Ah, thanks! I see here: 

https://github.com/vuemontreal/vuemontreal/blob/1722790d4225b7eaf6f0a4f8298d78fc97b44250/pages/events/_eventId.vue#L142-L146

This should be part of another PR to stick to the original issue scope. 
I'll merge this one since the fix is valid. 

@aurelienroux please open another issue / PR for the slider. Thanks!

**Comment by aurelienroux** [comment]
@f3ltron  yep I'll work on the slider this week. should be done before friday I think

**Pull request merged**
